---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubelink
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: kubelink.kubelink1.ringdev.shoot.dev.k8s-hana.ondemand.com
    dns.gardener.cloud/ttl: "500"
  name: kubelink
  namespace: kube-system
spec:
  selector:
    app: kubelink
    component: kubelink-broker
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8188
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubelink-broker
    component: kubelink-broker
  name: kubelink-broker
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubelink
      component: kubelink-broker
  template:
    metadata:
      labels:
        app: kubelink
        component: kubelink-broker
    spec:
      hostNetwork: true
      containers:
        - name: broker
          image: mandelsoft/kubelink:latest
          imagePullPolicy: "Always"
          args:
            - --controllers=broker
            - --secret=kubelink
            - --server-port-http=8180
            - --broker-port=8188
            - --pod-cidr=100.96.0.0/11
            - --node-cidr=10.250.0.0/16
            - --link-address=192.168.0.11/24
            - --ifce-name=kubelink
            - --service-cidr=100.64.0.0/20
            - --ipip
          securityContext:
            privileged: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8180
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8180
              protocol: TCP
            - containerPort: 8188
              protocol: TCP
          resources:
            {}

      serviceAccountName: kubelink
      terminationGracePeriodSeconds: 120

