apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  kubelink.server: |
    kubelink:8053 {
            errors
            cache 30
            forward . 100.64.16.11 # change-me
        }
